apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../infrastructure/configs/
patches:
  - patch: |-
      - op: replace
        path: /metadata/namespace
        value: apps
    target:
      kind: Gateway
  - patch: |-
      - op: replace
        path: /metadata/namespace
        value: apps
    target:
      kind: VirtualService
  - patch: |-
      - op: replace
        path: /spec/commonName
        value: staging.aks.tuilakhanh.id.vn
      - op: replace
        path: /spec/dnsNames/0
        value: staging.aks.tuilakhanh.id.vn
    target:
      kind: Certificate
      name: apps-letsencrypt-certs
  - patch: |-
      - op: replace
        path: /spec/acme/server
        value: https://acme-staging-v02.api.letsencrypt.org/directory
    target:
      kind: ClusterIssuer
      name: letsencrypt
  - patch: |-
      - op: replace
        path: /spec/servers/0/hosts/0
        value: staging.aks.tuilakhanh.id.vn
      - op: replace
        path: /spec/servers/1/hosts/0
        value: staging.aks.tuilakhanh.id.vn
    target:
      kind: Gateway
      name: api-gateway
  - patch: |-
      - op: replace
        path: /spec/hosts/0
        value: staging.aks.tuilakhanh.id.vn
    target:
      kind: VirtualService
      name: apps-vs