apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: staging-images
  namespace: flux-system
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: aks-flux-extension
  git:
    checkout:
      ref:
        branch: master
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: |
        [staging] update image tags
        
        Automated staging image update:
        - Image: {{ .Updated.Name }}
        - Tag: {{ .Updated.OldTag }} -> {{ .Updated.NewTag }}
    push:
      branch: master
  update:
    path: ./apps/staging
    strategy: Setters