apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: product-service-staging
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: product-service
  policy:
    semver:
      range: '>=v1.1.0-alpha.0 <v1.2.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: order-service-staging
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: order-service
  policy:
    semver:
      range: '>=v1.1.0-alpha.0 <v1.2.0' 
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: inventory-service-staging
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: inventory-service
  policy:
    semver:
      range: '>=v1.1.0-alpha.0 <v1.2.0'
