apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  labels:
    app: inventory-service
spec:
  selector:
    app: inventory-service
  ports:
  - name: grpc
    port: 50051
    targetPort: 50051
  type: ClusterIP