---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: istio
  namespace: cluster-config
spec:
  interval: 24h
  url: https://istio-release.storage.googleapis.com/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-base
  namespace: cluster-config
spec:
  releaseName: istio-base
  targetNamespace: istio-system
  interval: 30m
  chart:
    spec:
      chart: base
      version: "1.x"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: cluster-config
      interval: 12h
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istiod
  namespace: cluster-config
spec:
  releaseName: istiod
  targetNamespace: istio-system
  interval: 30m
  dependsOn:
    - name: istio-base
  chart:
    spec:
      chart: istiod
      version: "1.x"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: cluster-config
      interval: 12h
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-ingress
  namespace: cluster-config
spec:
  releaseName: istio-ingress
  targetNamespace: istio-system
  interval: 30m
  dependsOn:
    - name: istiod
  chart:
    spec:
      chart: gateway
      version: "1.x"
      sourceRef:
        kind: HelmRepository
        name: istio
        namespace: cluster-config
      interval: 12h