apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps-production
resources:
- namespace.yaml
- ../base
# patches:
# - path: product-patch.yaml
#   target:
#     kind: Deployment
#     name: product-service
# - path: order-patch.yaml
#   target:
#     kind: Deployment
#     name: order-service
# - path: inventory-patch.yaml
#   target:
#     kind: Deployment
#     name: inventory-service
images:
- name: order-service
  newName: groupthreesix.azurecr.io/order-service # {"$imagepolicy": "flux-system:order-service-production:name"}
  newTag: v1.1.0 # {"$imagepolicy": "flux-system:order-service-production:tag"}
- name: product-service
  newName: groupthreesix.azurecr.io/product-service # {"$imagepolicy": "flux-system:product-service-production:name"}
  newTag: v1.1.1 # {"$imagepolicy": "flux-system:product-service-production:tag"} 
- name: inventory-service
  newName: groupthreesix.azurecr.io/inventory-service # {"$imagepolicy": "flux-system:inventory-service-production:name"}
  newTag: v1.1.1 # {"$imagepolicy": "flux-system:inventory-service-production:tag"}
