apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ../base
patches:
- path: resources.yaml
  target:
    kind: Deployment

images:
- name: order-service
  newName: groupthreesix.azurecr.io/order-service
  newTag: latest
- name: product-service
  newName: groupthreesix.azurecr.io/product-service
  newTag: latest
- name: inventory-service
  newName: groupthreesix.azurecr.io/inventory-service
  newTag: latest