apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps-production

resources:
- namespace.yaml
- ../base

patches:
- path: product-patch.yaml
  target:
    kind: Deployment
    name: product-service
- path: order-patch.yaml
  target:
    kind: Deployment
    name: order-service
- path: inventory-patch.yaml
  target:
    kind: Deployment
    name: inventory-service

images:
- name: order-service
  newName: groupthreesix.azurecr.io/order-service
  newTag: latest
- name: product-service
  newName: groupthreesix.azurecr.io/product-service
  newTag: latest
- name: inventory-service
  newName: groupthreesix.azurecr.io/inventory-service
  newTag: latest