apiVersion: apps/v1
kind: Deployment
metadata:
  name: not-important
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: not-important
        resources:
          limits:
            memory: 1Gi
            cpu: "1"
          requests:
            memory: 512Mi
            cpu: "0.5"