apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: apps-letsencrypt-certs
  namespace: aks-istio-ingress
spec:
  secretName: apps-certs # letsencrypt certificate secret name, should match the credentialName in the gateway resource
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: apps.tuilakhanh.id.vn
  dnsNames:
    - apps.tuilakhanh.id.vn # this should match a host name in the gateway resource