apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps

resources:
- namespace.yaml
- ../base

images:
- name: order-service
  newName: groupthreesix.azurecr.io/order-service # {"$imagepolicy": "flux-system:order-service-staging"}
  newTag: latest # {"$imagepolicy": "flux-system:order-service-staging"}
- name: product-service
  newName: groupthreesix.azurecr.io/product-service # {"$imagepolicy": "flux-system:product-service-staging"}
  newTag: latest # {"$imagepolicy": "flux-system:product-service-staging"}
- name: inventory-service
  newName: groupthreesix.azurecr.io/inventory-service # {"$imagepolicy": "flux-system:inventory-service-staging"}
  newTag: latest # {"$imagepolicy": "flux-system:inventory-service-staging"}
