apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: apps
resources:
- namespace.yaml
- ../base
images:
- name: order-service
  newName: groupthreesix.azurecr.io/order-service:v1.1.0-alpha.12 # {"$imagepolicy": "flux-system:order-service-staging"}
  newTag: groupthreesix.azurecr.io/order-service:v1.1.0-alpha.12 # {"$imagepolicy": "flux-system:order-service-staging"}
- name: product-service
  newName: groupthreesix.azurecr.io/product-service:v1.1.0-alpha.12 # {"$imagepolicy": "flux-system:product-service-staging"}
  newTag: groupthreesix.azurecr.io/product-service:v1.1.0-alpha.12 # {"$imagepolicy": "flux-system:product-service-staging"}
- name: inventory-service
  newName: groupthreesix.azurecr.io/inventory-service:v1.1.0-alpha.12 # {"$imagepolicy": "flux-system:inventory-service-staging"}
  newTag: groupthreesix.azurecr.io/inventory-service:v1.1.0-alpha.12 # {"$imagepolicy": "flux-system:inventory-service-staging"}
